#version: '3.8'
services:
  develop:
    build:
      context: ..
      dockerfile: dockerfiles/dockerfile-dev/Dockerfile
    ports:
      - "2222:22"
    depends_on:
      - db
  db:
    build:
      context: ..
      dockerfile: dockerfiles/dockerfile-postgres/Dockerfile
    ports:
      - "5436:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data