version: '3.1'

services:
  db:
    build:
      context: .
      dockerfile: dockerfiles/dockerfile-postgres/Dockerfile
    ports:
      - "5435:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
