version: '3.1'

services:
  db:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_USER: spatialdatauser
      POSTGRES_PASSWORD: spatialdatapassword
      POSTGRES_DB: spatialdatadb
    ports:
      - "5435:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data